### ISSUE TITLE
mnist example: non-existent user directories causes "no such file or directory" errors

### ISSUE THREAD

**Issue by xyhuang** [mlperf/mlcube#143]
The directories for data, models and logs specified in user's run config file must exist before running the task, else "no such file or directory" errors might be triggered.

**Comment by sergey-serebryakov** [comment]
It will be fixed in [mlcube_examples](https://github.com/mlperf/mlcube_examples) repo, PR - [7](https://github.com/mlperf/mlcube_examples/pull/7)
