### ISSUE TITLE
Decide Project name for release 0.1

### ISSUE THREAD

**Issue by sub-mod** [mlperf/mlcube#48]
Decide on a project name & License.
Currently, Google search will result for mlbox will result in this project https://mlbox.readthedocs.io/en/latest/

**Comment by sub-mod** [comment]
We already have https://pypi.org/project/mlperf-compliance/
So `mlperf-mlbox` could be package name.

I am going to keep it here and get everyone to vote on that.

**Comment by ivotron** [comment]
`mlperf-mlbox` sounds like a good alternative. Should we vote with a thumbs up on the above https://github.com/mlperf/mlbox/issues/48#issuecomment-670655755?

**Comment by sub-mod** [comment]
> `mlperf-mlbox` sounds like a good alternative. Should we vote with a thumbs up on the above [#48 (comment)](https://github.com/mlperf/mlbox/issues/48#issuecomment-670655755)?

Thumps up for YES :)

**Comment by xyhuang** [comment]
since there is already a popular project named MLBox which is not our MLBox, how about considering a "non-mlbox" name to avoid confusion and potential branding issues?
also i guess we might need @TheKanter 's advice regarding alignment with our future branding

**Comment by petermattson** [comment]
Hi Folks,

It's an unfortunate naming collision.

However, Box should likely be branded around MLCommons rather than MLPerf.

Would be good to have a standard naming convention. Maybe something like:

mlcBox

And just call it "Box" verbally. What do you think?

Would also be good to loop in our branding people over next 1-2 months.
When do we need answer by?

Best,

Peter

**Comment by sub-mod** [comment]
>...be branded around MLCommons rather than MLPerf.

ok.

> When do we need answer by?

@petermattson  please involve the branding people . Getting a name in before Aug 21  would be helpful for the 0.1 release.

**Comment by xyhuang** [comment]
maybe we can use an internal name like "box"/"mlbox" for internal/pre releases, and decide on a more formal name once the branding folks are ready and before announcement to broader public

**Comment by sub-mod** [comment]
@petermattson any updates on this ?

**Comment by sub-mod** [comment]
closing this as we renamed to mlcube.
