### ISSUE TITLE
move old readme according to new directory structure

### ISSUE THREAD

**Issue by hshaikqct** [mlperf/mlcube#82]
While validating the Document published:https://mlperf.github.io/mlbox/

(mlbox) PS C:\mlperf\mlbox> dir

    Directory: C:\mlperf\mlbox

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         9/1/2020   2:22 AM                .github
d-----         9/1/2020   2:22 AM                docs
d-----         9/1/2020   2:22 AM                examples
d-----         9/1/2020   2:22 AM                mlcommons_box
d-----         9/1/2020   2:22 AM                runners
------         9/1/2020   2:22 AM           1225 .gitignore
------         9/1/2020   2:22 AM          11357 LICENSE
------         9/1/2020   2:22 AM             75 mkdocs-requirements.txt
------         9/1/2020   2:22 AM            666 mkdocs.yml
------         9/1/2020   2:22 AM           1698 README.md
------         9/1/2020   2:22 AM             23 requirements.txt
------         9/1/2020   2:22 AM           1254 setup.py

(mlbox) PS C:\mlperf\mlbox> pip install .
Processing c:\mlperf\mlbox
    ERROR: Command errored out with exit status 1:

    error: package directory 'mlbox' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sub-mod** [comment]
closing this @hshaikqct 
Kindly open a new issues for mlcube.
